//! RidePay — Soroban smart contract
//!
//! Settles USDC micropayments between riders and informal transport operators.
//! Works with any Stellar USDC anchor and any local fiat currency.
//!
//! Core flow
//! ─────────
//!   1. Operator initialises contract with USDC and loyalty token addresses.
//!   2. For each completed trip, `settle_ride` is called:
//!        a. Transfers USDC from rider → operator.
//!        b. Mints 1 loyalty token to the operator.
//!        c. Stores an immutable RideRecord keyed by ride_id.
//!        d. Emits a `RideSettled` event for off-chain listeners.

#![no_std]

use soroban_sdk::{
    contract, contractimpl, contracttype,
    token::Client as TokenClient,
    Address, Env, String, Symbol,
};

// ─── Storage keys ─────────────────────────────────────────────────────────────

/// Keys used for persistent and instance storage.
#[contracttype]
pub enum DataKey {
    /// Maps ride_id (String) → RideRecord
    Ride(String),
    /// USDC token contract address
    UsdcToken,
    /// Loyalty token contract address (issued by the operator or platform)
    LoyaltyToken,
    /// Contract admin address
    Admin,
    /// Total number of rides settled — useful for dashboards
    RideCount,
}

// ─── Data structures ──────────────────────────────────────────────────────────

/// Immutable record written once when a fare is settled.
#[contracttype]
#[derive(Clone)]
pub struct RideRecord {
    /// Stellar address of the operator (fare recipient)
    pub operator: Address,
    /// Stellar address of the rider (fare payer)
    pub rider: Address,
    /// Fare amount in USDC stroops (7 decimal places).
    /// Example: 1_000_000 stroops = 0.1 USDC
    pub usdc_amount: i128,
    /// Unix timestamp at settlement (sourced from ledger)
    pub settled_at: u64,
}

// ─── Contract ─────────────────────────────────────────────────────────────────

#[contract]
pub struct RidePayContract;

#[contractimpl]
impl RidePayContract {

    // ── Initialisation ────────────────────────────────────────────────────────

    /// Deploy-time setup. Must be called exactly once.
    ///
    /// # Arguments
    /// * `admin`         – deployer / platform operator address
    /// * `usdc_token`    – USDC token contract address on the target Stellar network
    /// * `loyalty_token` – Custom loyalty/reward token contract address
    pub fn initialize(
        env: Env,
        admin: Address,
        usdc_token: Address,
        loyalty_token: Address,
    ) {
        // Guard: prevent re-initialisation
        if env.storage().instance().has(&DataKey::Admin) {
            panic!("contract already initialised");
        }
        admin.require_auth();

        env.storage().instance().set(&DataKey::Admin, &admin);
        env.storage().instance().set(&DataKey::UsdcToken, &usdc_token);
        env.storage().instance().set(&DataKey::LoyaltyToken, &loyalty_token);
        env.storage().instance().set(&DataKey::RideCount, &0_u64);
    }

    // ── Core MVP function ─────────────────────────────────────────────────────

    /// Settle a single transport fare on-chain.
    ///
    /// Steps
    /// ─────
    ///   1. Validates that `usdc_amount` is positive.
    ///   2. Rejects duplicate `ride_id` submissions (idempotency guard).
    ///   3. Requires authorisation from both rider and operator.
    ///   4. Transfers USDC from rider → operator.
    ///   5. Transfers 1 loyalty token from this contract's reserve → operator.
    ///   6. Persists a `RideRecord` keyed by `ride_id`.
    ///   7. Increments the global ride counter.
    ///   8. Emits a `RideSettled` event.
    ///
    /// # Arguments
    /// * `ride_id`     – unique identifier for this trip (generated by the client app)
    /// * `rider`       – address of the paying passenger
    /// * `operator`    – address of the transport operator receiving the fare
    /// * `usdc_amount` – fare in USDC stroops (must be > 0)
    pub fn settle_ride(
        env: Env,
        ride_id: String,
        rider: Address,
        operator: Address,
        usdc_amount: i128,
    ) -> RideRecord {
        // Validate fare is non-zero
        if usdc_amount <= 0 {
            panic!("fare amount must be greater than zero");
        }

        // Idempotency: reject if this ride has already been settled
        let ride_key = DataKey::Ride(ride_id.clone());
        if env.storage().persistent().has(&ride_key) {
            panic!("ride already settled");
        }

        // Both parties must sign the transaction
        rider.require_auth();
        operator.require_auth();

        // Load token addresses from initialised storage
        let usdc_addr: Address = env
            .storage()
            .instance()
            .get(&DataKey::UsdcToken)
            .unwrap();
        let loyalty_addr: Address = env
            .storage()
            .instance()
            .get(&DataKey::LoyaltyToken)
            .unwrap();

        // Transfer USDC fare from rider to operator
        // The rider must have pre-authorised this contract as a spender
        let usdc = TokenClient::new(&env, &usdc_addr);
        usdc.transfer(&rider, &operator, &usdc_amount);

        // Award 1 loyalty token to the operator from this contract's reserve
        // The loyalty token contract must have minted a reserve to this contract at deploy time
        let loyalty = TokenClient::new(&env, &loyalty_addr);
        loyalty.transfer(&env.current_contract_address(), &operator, &1_i128);

        // Build and store the ride record
        let record = RideRecord {
            operator: operator.clone(),
            rider: rider.clone(),
            usdc_amount,
            settled_at: env.ledger().timestamp(),
        };
        env.storage().persistent().set(&ride_key, &record);

        // Increment global ride counter
        let count: u64 = env
            .storage()
            .instance()
            .get(&DataKey::RideCount)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&DataKey::RideCount, &(count + 1));

        // Emit event for indexers and the front-end WebSocket listener
        env.events().publish(
            (Symbol::new(&env, "RideSettled"), ride_id),
            (operator, rider, usdc_amount),
        );

        record
    }

    // ── Read helpers ──────────────────────────────────────────────────────────

    /// Retrieve a settled ride record by its ID.
    pub fn get_ride(env: Env, ride_id: String) -> RideRecord {
        env.storage()
            .persistent()
            .get(&DataKey::Ride(ride_id))
            .unwrap_or_else(|| panic!("ride not found"))
    }

    /// Return the total number of rides settled through this contract.
    pub fn ride_count(env: Env) -> u64 {
        env.storage()
            .instance()
            .get(&DataKey::RideCount)
            .unwrap_or(0)
    }
}
